services:
  # API Server Service (connects to existing PostgreSQL)
  api-server:
    image: node:18-alpine
    container_name: ${API_CONTAINER_NAME:-dual-agent-api}
    restart: unless-stopped
    working_dir: /app
    environment:
      # Database Configuration (connects to existing PostgreSQL on host)
      - DB_TYPE=postgresql
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5434
      - POSTGRES_DB=${POSTGRES_DB:-dual_agent_monitor}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dual_agent_secure_pass_2025}
      - POSTGRES_MAX_CONNECTIONS=${POSTGRES_MAX_CONNECTIONS:-20}
      - POSTGRES_SSL=false
      
      # Application Configuration
      - NODE_ENV=${NODE_ENV:-production}
      - WEBSOCKET_SERVER_PORT=${WEBSOCKET_SERVER_PORT:-4005}
      - API_BASE_URL=http://localhost:4005/api
      
      # Security Configuration
      - JWT_SECRET=${JWT_SECRET:-dual-agent-jwt-secret-key-minimum-32-chars-2025}
      - SESSION_SECRET=${SESSION_SECRET:-dual-agent-session-secret-key-minimum-32-chars-2025}
      
      # Logging Configuration
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-json}
    ports:
      - "${WEBSOCKET_SERVER_PORT:-4005}:4005"
    volumes:
      - ./:/app:ro
      - api_logs:/app/logs
    networks:
      - dual-agent-network
    command: >
      sh -c "
        echo 'Installing dependencies and starting API server...' &&
        apk add --no-cache wget curl &&
        npm install -g pnpm tsx &&
        cd /app &&
        echo 'Installing pnpm dependencies...' &&
        pnpm install --prod --ignore-scripts --silent &&
        echo 'Starting API server...' &&
        npx tsx server/websocket-server-minimal.ts
      "
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4005/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

volumes:
  api_logs:
    driver: local

networks:
  dual-agent-network:
    external: true