version: '3.8'

services:
  dual-agent-monitor:
    build: .
    ports:
      - "6011:6011"  # Frontend (via reverse proxy)
      - "4005:4005"  # Backend API and WebSocket
    volumes:
      - ./.dual-agent-sessions:/app/.dual-agent-sessions
      - ../logs:/app/logs  # Mount logs from parent directory if available
    environment:
      - NODE_ENV=production
      - PORT=4005
      - WEBSOCKET_SERVER_PORT=4005
    restart: unless-stopped
    
  # Nginx reverse proxy to serve frontend on port 6011
  nginx:
    image: nginx:alpine
    ports:
      - "6011:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist/client:/usr/share/nginx/html:ro
    depends_on:
      - dual-agent-monitor
    restart: unless-stopped