name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '20'

jobs:
  # Main project build and test
  build-main:
    name: Build Main Project
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build project
      run: pnpm run build

    - name: Run linting
      run: pnpm run lint
      continue-on-error: true

    - name: Run type checking
      run: pnpm run typecheck
      continue-on-error: true

    - name: Test CLI
      run: |
        node dist/index.js --version
        node dist/index.js --help
        node dist/index.js examples

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-main
        path: dist/
        retention-days: 7

  # Docker build test
  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        tags: automatic-claude-code:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test Docker image
      run: |
        docker run --rm automatic-claude-code:test node dist/index.js --version
        docker run --rm automatic-claude-code:test node dist/index.js --help

  # Monitoring dashboard build
  monitor-build:
    name: Build Monitoring Dashboard
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install dependencies (monitoring)
      run: |
        cd dual-agent-monitor
        if [ -f "pnpm-lock.yaml" ]; then
          pnpm install --frozen-lockfile
        else
          npm ci
        fi

    - name: Type checking (monitoring)
      run: |
        cd dual-agent-monitor
        npm run typecheck || echo "Type checking failed, continuing..."
      continue-on-error: true

    - name: Build monitoring dashboard
      run: |
        cd dual-agent-monitor
        npm run client:build || echo "Client build failed, continuing..."
        npm run server:build || echo "Server build failed, continuing..."
      continue-on-error: true

    - name: Check build output
      run: |
        cd dual-agent-monitor
        ls -la dist/ 2>/dev/null || echo "No dist directory found"
        ls -la server/*.js 2>/dev/null || echo "No compiled server files found"

  # Simple integration test
  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: [build-main]
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Build project
      run: pnpm run build

    - name: Start monitoring server
      run: |
        node monitoring-server.js &
        sleep 5
      continue-on-error: true

    - name: Test monitoring health endpoint
      run: |
        curl -f http://localhost:6007/health || echo "Health check failed"
      continue-on-error: true

    - name: Test monitoring API
      run: |
        curl -f http://localhost:6007/api/status || echo "API status check failed"
      continue-on-error: true

  # Security scan
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Run audit
      run: pnpm audit --audit-level=high
      continue-on-error: true

    - name: Check for known vulnerabilities
      run: |
        echo "Checking for vulnerabilities..."
        pnpm audit --json > audit-report.json || true
        cat audit-report.json | jq '.metadata.vulnerabilities' || echo "No vulnerabilities section found"
      continue-on-error: true

  # All tests pass check
  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    needs: [build-main, docker-build, monitor-build, integration-test, security-scan]
    if: always()
    
    steps:
    - name: Check job results
      run: |
        echo "Build Main: ${{ needs.build-main.result }}"
        echo "Docker Build: ${{ needs.docker-build.result }}"
        echo "Monitor Build: ${{ needs.monitor-build.result }}"
        echo "Integration Test: ${{ needs.integration-test.result }}"
        echo "Security Scan: ${{ needs.security-scan.result }}"
        
        # Fail if critical jobs failed
        if [ "${{ needs.build-main.result }}" != "success" ]; then
          echo "Main build failed!"
          exit 1
        fi
        
        if [ "${{ needs.docker-build.result }}" != "success" ]; then
          echo "Docker build failed!"
          exit 1
        fi
        
        echo "✅ CI Pipeline completed successfully!"